### PR TITLE
Mac c make

### LINKED ISSUE #23: Unable to compile on Macbook Pro M2 Max, Mac OS 13.4.1
Receive the following errors:

(base) alaferri@Alisons-MBP build % cmake ..
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Clang detected
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Clang detected
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/alaferri/GIT/bellhopcuda/build

(base) alaferri@Alisons-MBP build % make
[  1%] Building CXX object config/cxx/CMakeFiles/bellhopcxxobjlib.dir/__/__/src/mode/arr.cpp.o
In file included from /Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:19:
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.hpp:82:37: error: no matching function for call to 'min'
        arrinfo->MaxNArr = (int32_t)std::min(
                                    ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:40:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'size_t' (aka 'unsigned long'))
min(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:51:1: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'unsigned long long'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:61:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:31:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:313:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '2D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:426:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<false, false>' requested here
template void ReadOutArrivals<false, false>(
              ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:430:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, false>' requested here
template void ReadOutArrivals<true, false>(
              ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:434:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, true>' requested here
template void ReadOutArrivals<true, true>(
              ^
4 errors generated.
make[2]: *** [config/cxx/CMakeFiles/bellhopcxxobjlib.dir/__/__/src/mode/arr.cpp.o] Error 1
make[1]: *** [config/cxx/CMakeFiles/bellhopcxxobjlib.dir/all] Error 2
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by oldstylejoe**
Changes to support compilation in Mac. Tested on mac in issue 23. Check on windows.

closes #23

### CODE REVIEW

**Review by kjaxon — APPROVED** [review]
Took about 15 mins to build but it successfully built.
