### ISSUE TITLE
Unable to compile on Macbook Pro M2 Max, Mac OS 13.4.1

### ISSUE THREAD

**Issue by alaferri** [A-New-BellHope/bellhopcuda#23]
Receive the following errors:

(base) alaferri@Alisons-MBP build % cmake ..
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Clang detected
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Clang detected
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/alaferri/GIT/bellhopcuda/build

(base) alaferri@Alisons-MBP build % make
[  1%] Building CXX object config/cxx/CMakeFiles/bellhopcxxobjlib.dir/__/__/src/mode/arr.cpp.o
In file included from /Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:19:
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.hpp:82:37: error: no matching function for call to 'min'
        arrinfo->MaxNArr = (int32_t)std::min(
                                    ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:40:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'size_t' (aka 'unsigned long'))
min(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:51:1: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'unsigned long long'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:61:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/min.h:31:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:313:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '2D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:426:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<false, false>' requested here
template void ReadOutArrivals<false, false>(
              ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:430:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, false>' requested here
template void ReadOutArrivals<true, false>(
              ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/bellhopcuda/src/mode/arr.cpp:434:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, true>' requested here
template void ReadOutArrivals<true, true>(
              ^
4 errors generated.
make[2]: *** [config/cxx/CMakeFiles/bellhopcxxobjlib.dir/__/__/src/mode/arr.cpp.o] Error 1
make[1]: *** [config/cxx/CMakeFiles/bellhopcxxobjlib.dir/all] Error 2
make: *** [all] Error 2

**Comment by oldstylejoe** [comment]
Thanks for the issue, and sorry for the slow response. This highlights some compiler implementation differences we're currently trying to figure out. If you have a chance, you can try the [MacCMake](https://github.com/A-New-BellHope/bellhopcuda/compare/main...MacCMake) branch? I don't have easy access to an M2, but that was a fix for an older MacBook.

**Comment by jdbosser** [comment]
Hi! I wanted to add in to this issue. I had trouble building this with cmake on my ubuntu 23.04 machine. I got errors on that 
```
bellhopcuda/src/util/prtfileemu.hpp:55:21: error: no match for ‘operator<<’ (operand types are ‘std::stringstream’ {aka ‘std::__cxx11::basic_stringstream<char>’} and ‘const glm::vec<2, double, glm::packed_highp>’)
   55 |             linebuf << x;
      |             ~~~~~~~~^~~~
```
Switching to the MacCMake branch seem to have solved this issue for me.

**Comment by alaferri** [comment]
Hi @oldstylejoe - thanks for your help. Sorry for my slow reply.  I tried the MacCMake branch but am now getting the following error:

`(base) alaferri@Alisons-MacBook-Pro build % cmake ..
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Clang detected
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Clang detected
-- Configuring done (0.4s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/alaferri/GIT/third_party_code/bellhopcuda/build
(base) alaferri@Alisons-MacBook-Pro build % make
[  1%] Building CXX object config/cxx/CMakeFiles/bellhopcxxobjlib.dir/__/__/src/mode/arr.cpp.o
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:313:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '2D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:426:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<false, false>' requested here
template void ReadOutArrivals<false, false>(
              ^
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:430:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, false>' requested here
template void ReadOutArrivals<true, false>(
              ^
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:308:84: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                "Incorrect dimensionality in arrivals file, must be '3D', got %s", dim);
                                                                                   ^
/Users/alaferri/GIT/third_party_code/bellhopcuda/src/mode/arr.cpp:434:15: note: in instantiation of function template specialization 'bhc::mode::ReadOutArrivals<true, true>' requested here
template void ReadOutArrivals<true, true>(
              ^
3 errors generated.
`

**Comment by oldstylejoe** [comment]
@alaferri  After an unfortunately long hiatus, I hopefully fixed the problem. If you're curious there's an [explanation here](https://stackoverflow.com/questions/62228109/error-cannot-pass-object-of-non-trivial-type-stdstring-and-more-errors)

If you're still around and interested, please update the MacCMake branch and try it out, or I can find someone else with an M2.

**Comment by alaferri** [comment]
@oldstylejoe - Sorry for the slow reply. I finally got around to giving this a try again and your fix did the trick. Thanks!!
